name: "Update hyprpm pin on latest Hyprland release"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly on Sunday 00:00
jobs:
  pin-latest-hyprland:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            extra-substituters = https://hyprland.cachix.org
            extra-trusted-public-keys = hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=
      - name: Update pins
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eu
          set -m   # workaround: I get "fg: no job control" even though I don't use any job control
          git fetch --depth=1 --tags origin main

          ./scripts/ci/pin-latest-hyprland origin/main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'ci: automated update of hyprpm.toml'
          title: 'Automated PR: Update hyprpm pin'
          body: 'This PR was created by a Github Actions workflow'

